### ISSUE TITLE
Support for Legacy category needed

### ISSUE THREAD

**Issue by tomrmyers** [International-Aerobatic-Club/iaccdb#168]
Jasper is now set up for 3 different contest types: powered, glider, and legacy. Results of Legacy contests need to be handled slightly differently than powered and glider. Legacy contest judge and assistant credits need to be compiled in the same way as for powered and glider contests. Legacy contest pilot results need to be posted in the same way as for powered and glider contests. Legacy contest pilot results are not compiled for seasonal series results. Every Legacy contest is stand-alone with regard to the pilot results.

**Comment by djmolny** [comment]
Additional details are at: https://www.iac.org/files/minutes/Agenda%20Item%2014.1%20Legacy%20Category%20Report%20Fall%202019.pdf

**Comment by wbreeze** [comment]
I'm not going to go deep into this for the moment, unless you ask me to. Off the top of my head, have a look at how the four minute free is handled. That might be very similar. Or I might be leading you astray. As in, probably, you want to make up a new aircat code or pair of them. Or maybe not.

Don't assume this is a slam dunk, make a new category and done. It probably requires some careful work. The reason for that is that you want one thing - judge credit - and not another - series calcs & etc. This division is a very new thing.

**Comment by djmolny** [comment]
Status update: This feature is on hold until the Board decides whether the Legacy category will be a permanent addition.

**Comment by tomrmyers** [comment]
thanx dj.

tom.

**Comment by djmolny** [comment]
OBE: Legacy is not going to become an official contest category due to lack of interest.
