### ISSUE TITLE
enable entry of Nationals Chief Judge assistants

### ISSUE THREAD

**Issue by wbreeze** [International-Aerobatic-Club/iaccdb#2]
The data import from ACRO does not provide these.  The ACRO outputs don't associate the assistants with the judges.

Depends on [AJAXy member picker](https://github.com/wbreeze/iaccdb/issues/5) in my opinion.

There has to be a way to

- authorize the interface for the change
- validate the member selection

On the other hand, it could go in admin and take an IAC member ID without question. That would be a valid make it work solution.

**Comment by wbreeze** [comment]
Depends on [AJAXy member picker](https://github.com/wbreeze/iaccdb/issues/5) in my opinion.  

There has to be a way to
- authorize the interface for the change
- validate the member selection

On the other hand, it could go in admin and take an IAC member ID without question.  That would be a valid make it work solution.

**Comment by djmolny** [comment]
OBE: we no longer transfer data from Acro to IACCDB.
