### ISSUE TITLE
"POST contests" doesn't report failures

### ISSUE THREAD

**Issue by djmolny** [International-Aerobatic-Club/iaccdb#43]
contests_controller.rb includes the following code:

```
# POST /contests
  def create
    contest = Contest.create(contest_params)
    if (contest)
      render json: contest
    else
      head :bad_request
  end
end
```

Unfortunately, the if statement always returns TRUE because the value of contest is never nil. If the Contest.create operation fails, Rails returns the unsaved Contest object plus errors. So that 'if' statement should actually read:

`        if (contest.valid?)
`
Then at least the POST will return the appropriate HTTP code (400).

It also would be very helpful if the 'else' clause generated a message body that describes the problem, thus:

 ```
    render json: { errors: contest.errors.full_messages }, status: 400
```

**Comment by wbreeze** [comment]
Closed with PR #45
